### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by robbymeals** [dropwizard-bundles/dropwizard-api-key-bundle#9]
Hi, we were hoping to use this bundle but since there's no license, I am a little wary. I see that all your other bundles are licensed under Apache, which totally works for us. Is it possible for you to add Apache license to this repo as well?
Thanks,
Rob

https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

**Comment by bbeck** [comment]
Hi Robby, not having a license file was an oversight.  I just added the Apache 2.0 license to the repo.

**Comment by robbymeals** [comment]
thanks!
